---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-install-tools"
      label: "Install Tools"
      solveButton: false
    - name: "02-run-bcc-tools"
      label: "Run Bcc Tools"
      solveButton: false
    - name: "03-file-ops"
      label: "File Ops"
      solveButton: false
    - name: "04-dnf"
      label: "Dnf"
      solveButton: false
    - name: "05-more-dnf"
      label: "More Dnf"
      solveButton: false
    - name: "06-other-tools"
      label: "Other Tools"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
